lvim.builtin.dap.active = true
-- lvim.builtin.dap.ui.config.layouts.position = "left"
-- lvim.builtin.dap.ui.config.layouts = { {
--         elements = { {
--             id = "scopes",
--             size = 0.25
--           }, {
--             id = "breakpoints",
--             size = 0.25
--           }, {
--             id = "stacks",
--             size = 0.25
--           }, {
--             id = "watches",
--             size = 0.25
--           } },
--         position = "left",
--         size = 40
--       }, {
--         elements = { {
--             id = "repl",
--             size = 0.5
--           }, {
--             id = "console",
--             size = 0.5
--           } },
--         position = "bottom",
--         size = 10
--       } }
require('dap.javascript')
require('dap.python')
